// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	model "content-producer-manager/pkg/model"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// SendRabbitMessage provides a mock function with given fields: content
func (_m *Repository) SendRabbitMessage(content *model.Metadata) error {
	ret := _m.Called(content)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Metadata) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
